image: node:lts

cache:
  untracked: true
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - install
  - lint
  - type check
  - test
  - build
  - deploy
  - test integration

install:
  stage: install
  image: cypress/base:10
  stage: build
  only:
    changes:
      - packages/components/**/*
      - .gitlab-ci.yml
  script:
    - yarn install --frozen-lockfile
    - $(yarn bin)/cypress cache path
    - $(yarn bin)/cypress cache list
    - $(yarn bin)/cypress verify

variables:
  PACKAGE_PATH_COMPONENTS: 'packages/components-storybook'
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  PACKAGE_PATH_SUITE_WEB: 'packages/suite-web'
  PACKAGE_PATH_SUITE_NATIVE: 'packages/suite-native'
  PACKAGE_PATH_SUITE_DESKTOP: 'packages/suite-desktop'
  PACKAGE_PATH_SUITE_ONBOARDING: 'packages/suite-onboarding'

  DEV_SERVER_URL: 'https://suite.corp.sldev.cz'

include:
  - ci/packages/components.yml
  - ci/packages/components-storybook.yml
  - ci/packages/suite.yml
  - ci/packages/suite-web.yml
  - ci/packages/suite-desktop.yml
  - ci/packages/suite-native.yml
  - ci/packages/suite-onboarding.yml