image: node:lts

cache:
    untracked: true
    key: ${CI_COMMIT_REF_NAME}
    paths:
        - node_modules/
        - cache/Cypress

before_script:
    - yarn install

stages:
    - install
    - lint
    - type check
    - test
    - build
    - deploy
    - test integration

install:
    stage: install
    image: cypress/base:10
    only:
        changes:
            - packages/components/**/*
            - .gitlab-ci.yml
    script:
        - apt-get update
        - apt-get install -y build-essential
        - apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 --assume-yes
        - yarn install --frozen-lockfile
        - yarn workspace @trezor/components build:lib
        - $(yarn bin)/cypress cache path
        - $(yarn bin)/cypress cache list
        - $(yarn bin)/cypress verify

variables:
    PACKAGE_PATH_COMPONENTS: 'packages/components-storybook'
    CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
    PACKAGE_PATH_SUITE_WEB: 'packages/suite-web'
    PACKAGE_PATH_SUITE_NATIVE: 'packages/suite-native'
    PACKAGE_PATH_SUITE_DESKTOP: 'packages/suite-desktop'
    PACKAGE_PATH_SUITE_ONBOARDING: 'packages/suite-onboarding'

    DEV_SERVER_URL: 'https://suite.corp.sldev.cz'

include:
    - ci/packages/components.yml
    - ci/packages/components-storybook.yml
    - ci/packages/suite.yml
    - ci/packages/suite-web.yml
    - ci/packages/suite-desktop.yml
    - ci/packages/suite-native.yml
    - ci/packages/suite-onboarding.yml
